build:
  version: "3.0"

product-microservice:
  message: "Product microservice"
  contactDetails:
    name: "Kurenkiev Timur - Developer"
    email: "kurenkievtimur@gmail.com"
  onCallSupport:
    - (999) 999-999
